name: emphasize
description: Lightweight customizable widget to highlight text, words or word groups within a text.
version: 1.1.1
homepage: https://github.com/caylab/emphasize

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: