name: emphasize
description: Lightweight customizable widget to display text with highlighted words or word groups.
version: 0.9.0
homepage: https://github.com/caylab/emphasize

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: