name: emphasize
description: Lightweight customizable widget to highlighted words or word groups in text.
version: 1.0.1
homepage: https://github.com/caylab/emphasize

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: